import { createThemes } from "tw-colors";
import { ColorTheme, Colors } from "./types";

const sharedColors = {
  skeleton: "rgba(128, 128, 128, 0.5)",
  white: "#FFFFFF",
  black: "#000000",
};

export const sand: ColorTheme = {
  background: "#EDD6B8",
  backgroundBright: "#F5E3CA",
  backgroundDark: "#D5B792",
  text: "#405759",
  button: "#405759B3",
  input: "#F2E4D2",
  placeholderText: "#808080",
  border: "#F2E4D2",
  primary: "#EDD6B8",
  primaryDark: "#EDD6B880",
  primaryBright: "#F2E4D2",
  secondary: "#D7A738",
  secondaryDark: "#D7A73880",
  secondaryBright: "#EBA738",
  error: "#D45D58",
  success: "#33CC33",
  warning: "#D4A357",
  info: "#547E9C",
  ...sharedColors,
};

export const softLight: ColorTheme = {
  primary: "#5E8B7E",
  primaryBright: "#81A89D",
  primaryDark: "#41605A",
  secondary: "#B5A27E",
  secondaryBright: "#D3BA9D",
  secondaryDark: "#8D7A5D",
  background: "#F5F5F2",
  backgroundBright: "#FAFAF7",
  backgroundDark: "#E0E0D7",
  text: "#353535",
  error: "#D45D58",
  success: "#6DA77A",
  warning: "#D4A357",
  info: "#62879B",
  placeholderText: "#A9A9A9",
  border: "#E0E0D7",
  input: "#FAFAF7",
  button: "#5E8B7E",
  ...sharedColors,
};

export const vibrant: ColorTheme = {
  primary: "#0099FF",
  primaryBright: "#33ADFF",
  primaryDark: "#0066CC",
  secondary: "#FF6600",
  secondaryBright: "#FF8833",
  secondaryDark: "#CC5200",
  background: "#F2F2F2",
  backgroundBright: "#FAFAFA",
  backgroundDark: "#E0E0E0",
  text: "#333333",
  error: "#FF3333",
  success: "#33CC33",
  warning: "#FFCC00",
  info: "#3399FF",
  placeholderText: "#999999",
  border: "#CCCCCC",
  input: "#FFFFFF",
  button: "#007ACC",
  ...sharedColors,
};

export const pastel: ColorTheme = {
  primary: "#A8D5E2",
  primaryBright: "#C5E7EF",
  primaryDark: "#86BACD",
  secondary: "#F3C6A7",
  secondaryBright: "#F5D2C1",
  secondaryDark: "#F0B290",
  background: "#F6F4F2",
  backgroundBright: "#FCF9F7",
  backgroundDark: "#E2DFDB",
  text: "#4A4A4A",
  error: "#FF3333",
  success: "#33CC33",
  warning: "#FFCC00",
  info: "#6A93B5",
  placeholderText: "#B2B2B2",
  border: "#DADADA",
  input: "#FAFAFA",
  button: "#83C1D4",
  ...sharedColors,
};

export const dark: ColorTheme = {
  primary: "#3949AB",
  primaryBright: "#5468D4",
  primaryDark: "#273593",
  secondary: "#00ACC1",
  secondaryBright: "#26C6DA",
  secondaryDark: "#008B9B",
  background: "#242424",
  backgroundBright: "#3A3A3A",
  backgroundDark: "#121212",
  text: "#E0E0E0",
  error: "#EF5350",
  success: "#66BB6A",
  warning: "#FFEE58",
  info: "#507AB3",
  placeholderText: "#9E9E9E",
  border: "#424242",
  input: "#333333",
  button: "#304FFE",
  ...sharedColors,
};

export const sunsetGlow: ColorTheme = {
  primary: "#FFADAD",
  primaryBright: "#FFD6A5",
  primaryDark: "#FF8484",
  secondary: "#FFC3A0",
  secondaryBright: "#FF9A3D",
  secondaryDark: "#FF773D",
  background: "#FFFBDF",
  backgroundBright: "#FFFFF0",
  backgroundDark: "#FFF7C0",
  text: "#393E46",
  error: "#FF2E63",
  success: "#21BF73",
  warning: "#FF9F1C",
  info: "#5A8BC2",
  placeholderText: "#BDB8B3",
  border: "#FEC5BB",
  input: "#FFFFFF",
  button: "#FDCA40",
  ...sharedColors,
};

export const greenForest: ColorTheme = {
  primary: "#2A9D8F",
  primaryBright: "#48B19E",
  primaryDark: "#20756C",
  secondary: "#F4A261",
  secondaryBright: "#F6BB67",
  secondaryDark: "#E89552",
  background: "#E9C46A",
  backgroundBright: "#F2D083",
  backgroundDark: "#D7AC51",
  text: "#264653",
  error: "#E76F51",
  success: "#2A9D8F",
  warning: "#F4A261",
  info: "#47798C",
  placeholderText: "#A89F91",
  border: "#B0A295",
  input: "#F1F1DC",
  button: "#2A9D8F",
  ...sharedColors,
};

export const gentlePink: ColorTheme = {
  primary: "#FFB6B9",
  primaryBright: "#FFD2D2",
  primaryDark: "#FF9295",
  secondary: "#ACD8AA",
  secondaryBright: "#C1E7C1",
  secondaryDark: "#9AC498",
  background: "#FFF5E1",
  backgroundBright: "#FFFBE8",
  backgroundDark: "#FFE6CC",
  text: "#6B4226",
  error: "#FF6B6B",
  success: "#32E875",
  warning: "#FFE156",
  info: "#5E96B3",
  placeholderText: "#BDB2A7",
  border: "#FEC2C2",
  input: "#FEF1E6",
  button: "#FFB6B9",
  ...sharedColors,
};

export const mysticPurple: ColorTheme = {
  primary: "#A663CC",
  primaryBright: "#C084F5",
  primaryDark: "#8539B2",
  secondary: "#63A6CC",
  secondaryBright: "#84C0F5",
  secondaryDark: "#3985B2",
  background: "#D8E3E7",
  backgroundBright: "#E4EEF2",
  backgroundDark: "#C1CED2",
  text: "#4A3F6B",
  error: "#E63946",
  success: "#50C878",
  warning: "#F4C430",
  info: "#636CB3",
  placeholderText: "#A5A5AF",
  border: "#BFA7D0",
  input: "#F2E9E4",
  button: "#A663CC",
  ...sharedColors,
};

export const earthyBrowns: ColorTheme = {
  primary: "#855C75",
  primaryBright: "#A67C8B",
  primaryDark: "#5F4257",
  secondary: "#D9BF77",
  secondaryBright: "#ECD4A0",
  secondaryDark: "#C2A655",
  background: "#F4ECE2",
  backgroundBright: "#FAF4E8",
  backgroundDark: "#E9DCD0",
  text: "#443C3C",
  error: "#DB5461",
  success: "#5E9648",
  warning: "#FFA26B",
  info: "#6D7B92",
  placeholderText: "#A8A391",
  border: "#BFA89E",
  input: "#EFE6DD",
  button: "#855C75",
  ...sharedColors,
};

export const freshMint: ColorTheme = {
  primary: "#89C9B8",
  primaryBright: "#A9DCD0",
  primaryDark: "#6AA693",
  secondary: "#F28C8C",
  secondaryBright: "#F4A7A7",
  secondaryDark: "#E56D6D",
  background: "#E2FAF7",
  backgroundBright: "#E9FDFC",
  backgroundDark: "#C9E8E0",
  text: "#285943",
  error: "#FF686B",
  success: "#52DE97",
  warning: "#FFAA64",
  info: "#5698A9",
  placeholderText: "#9DA9A0",
  border: "#B1D4C4",
  input: "#EAF6F1",
  button: "#89C9B8",
  ...sharedColors,
};

export const electricBlue: ColorTheme = {
  primary: "#0033CC",
  primaryBright: "#0055FF",
  primaryDark: "#0022AA",
  secondary: "#33CCFF",
  secondaryBright: "#66DFFF",
  secondaryDark: "#00B2CC",
  background: "#D6EFFF",
  backgroundBright: "#E2F2FF",
  backgroundDark: "#B9D6F2",
  text: "#002244",
  error: "#FF5050",
  success: "#4CAF50",
  warning: "#FFCC00",
  info: "#2D7ABD",
  placeholderText: "#7D9DBD",
  border: "#A7C7E7",
  input: "#E1F0FC",
  button: "#0033CC",
  ...sharedColors,
};

export const redAlert: ColorTheme = {
  primary: "#FF3D3D",
  primaryBright: "#FF6E6E",
  primaryDark: "#D00000",
  secondary: "#FA8334",
  secondaryBright: "#FC9D5B",
  secondaryDark: "#E66A09",
  background: "#FFF8F0",
  backgroundBright: "#FFFCF7",
  backgroundDark: "#FFE1D6",
  text: "#520202",
  error: "#D00000",
  success: "#50C878",
  warning: "#FFBA49",
  info: "#8571B1",
  placeholderText: "#A58D8D",
  border: "#FF8686",
  input: "#FFF1E6",
  button: "#FF3D3D",
  ...sharedColors,
};

export const goldenGlam: ColorTheme = {
  primary: "#FFD700",
  primaryBright: "#FFE833",
  primaryDark: "#D4AF37",
  secondary: "#C0C0C0",
  secondaryBright: "#D7D7D7",
  secondaryDark: "#A8A8A8",
  background: "#FFF4E0",
  backgroundBright: "#FFFAF2",
  backgroundDark: "#FFE0C0",
  text: "#4A3822",
  error: "#D32F2F",
  success: "#388E3C",
  warning: "#FBC02D",
  info: "#6A80A7",
  placeholderText: "#ADA07A",
  border: "#E6C08A",
  input: "#FFFAE5",
  button: "#FFD700",
  ...sharedColors,
};

export const allThemes: Record<string, ColorTheme> = {
  light: softLight,
  sand: sand,
  dark: dark,
  vibrant: vibrant,
  pastel: pastel,
  sunsetGlow: sunsetGlow,
  greenForest: greenForest,
  gentlePink: gentlePink,
  mysticPurple: mysticPurple,
  earthyBrowns: earthyBrowns,
  freshMint: freshMint,
  electricBlue: electricBlue,
  redAlert: redAlert,
  goldenGlam: goldenGlam,
};

export const theme = createThemes({
  light: softLight,
  sand: sand,
  dark: dark,
  vibrant: vibrant,
  pastel: pastel,
  sunsetGlow: sunsetGlow,
  greenForest: greenForest,
  gentlePink: gentlePink,
  mysticPurple: mysticPurple,
  earthyBrowns: earthyBrowns,
  freshMint: freshMint,
  electricBlue: electricBlue,
  redAlert: redAlert,
  goldenGlam: goldenGlam,
});

export const colorSafelist = Object.keys(softLight).map((color) => {
  return `bg-${color} text-${color} border-${color} placeholder-${color} fill-${color} focus:ring-${color} after:bg-${color} shadow-${color}`;
});

export const colorSafelistForStorybookOnly = Object.entries(allThemes)
  .flatMap(([, theme]) => Object.values(theme))
  .map((color) => {
    return `bg-[${color}]`;
  });
